# Gitleaks configuration for JD-GUI Enhanced
# This file defines custom patterns for detecting secrets and API keys

title = "JD-GUI Enhanced Gitleaks Configuration"

[extend]
# Include default Gitleaks rules
useDefault = true

# Custom rules for specific API keys and patterns
[[rules]]
id = "virustotal-api-key"
description = "VirusTotal API Key"
regex = '''(?i)(virustotal[_-]?api[_-]?key|vt[_-]?key|virus[_-]?total)['":\s=]*['"]*([a-f0-9]{64})['"]*'''
keywords = ["virustotal", "vtkey", "vt_key"]

[[rules]]
id = "generic-api-key-64-char"
description = "Generic 64-character hex API key"
regex = '''(?i)(api[_-]?key|apikey|key|secret)['":\s=]*['"]*([a-f0-9]{64})['"]*'''
keywords = ["apikey", "api_key", "secret"]

[[rules]]
id = "java-properties-secrets"
description = "Secrets in Java properties files"
regex = '''(?i)(password|secret|key|token)[=:]\s*['"]*([^'"\s]{8,})['"]*'''
path = '''\.properties$'''

[[rules]]
id = "environment-variables"
description = "Environment variable secrets"
regex = '''(?i)(export\s+|ENV\s+)([A-Z_]*(?:PASSWORD|SECRET|KEY|TOKEN)[A-Z_]*)=['"]*([^'"\s]{8,})['"]*'''

# Global allowlist for test patterns and safe files
[allowlist]
description = "Global allowlist for test patterns and documentation"
regexes = [
  '''(?i)(test|dummy|fake|example|sample)[_-]?(key|token|secret|password)''',
  '''(0{8,}|1{8,}|a{8,}|f{8,})''',
  '''(0123456789abcdef){2,}''',
  '''[a-f0-9]{64}.*(test|example|dummy)''',
  '''(ABCDEF0123456789|A1b2C3d4E5f6)''',
]

paths = [
  '''.*\.md$''',
  '''.*\.txt$''',
  '''.*\.example$''',
  '''.*\.template$''',
  '''.*\.sample$''',
  '''.*/test.*\.java$''',
  '''.*/Test.*\.java$''',
  '''.*test.*\.java$''',
  '''.*Test.*\.java$''',
  '''.*/tests?/.*$''',
  '''.*/examples?/.*$''',
  '''.*/samples?/.*$''',
]