# Pre-commit hooks for JD-GUI Enhanced security
repos:
  # Secret detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks

  # Alternative secret scanner
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            .*\.lock|
            .*\.png|
            .*\.jpg|
            .*\.jpeg|
            .*\.gif|
            .*\.jar|
            .*\.class
          )$

  # General security and quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']  # Prevent large files (potential binaries with secrets)
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Java-specific checks
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  # Additional security scanning for Java
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        files: \.py$

# Configuration
default_stages: [commit, push]
fail_fast: false