name: Continuous Integration

on:
  push:
    branches: [ master, develop, feature-* ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: ['8', '11', '17']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable (Unix)
      if: runner.os != 'Windows'
      run: chmod +x gradlew

    - name: Initialize submodules
      run: |
        git submodule init
        git submodule update

    - name: Build project
      run: ./gradlew build --no-daemon

    - name: Run tests
      run: ./gradlew test --no-daemon

    - name: Build Windows executable (Windows only)
      if: runner.os == 'Windows'
      run: ./gradlew buildExe --no-daemon

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results-${{ matrix.os }}-java${{ matrix.java }}
        path: |
          **/build/reports/tests/**
          **/build/test-results/**

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Initialize submodules
      run: |
        git submodule init
        git submodule update

    - name: Run checkstyle (if available)
      run: ./gradlew checkstyleMain checkstyleTest --no-daemon --continue || true

    - name: Run spotbugs (if available)
      run: ./gradlew spotbugsMain spotbugsTest --no-daemon --continue || true

    - name: Generate build scan
      run: ./gradlew build --scan --no-daemon || true